version: '3.3'

services:
  app:
    build:
      context: ./docker/php
    expose:
      - 9000
    network_mode: bridge
    restart: always
    user: 1000:1000
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./docker/php/custom.ini://usr/local/etc/php/conf.d/custom.ini:rw
      - .:/var/www/app/www:rw
    working_dir: /var/www/app/www
  nginx:
    image: nginx:stable-alpine
    environment:
      VIRTUAL_HOST: api.smt.loc
    expose:
    - 80
    links:
    - app
    network_mode: bridge
    restart: always
    volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www/app/www:rw
